[build]
  publish = "public"
  environment = { NPM_FLAGS = "--legacy-peer-deps" }

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[[redirects]]
from = "/resume"
to = "/jidicula-resume/jidicula-resume.pdf"
status = 301
